version: "3.11.1"
services:
  db:
    image: postgres:15
    container_name: db_app
    ports:
      - 5438:5432
    env_file:
      - .env_example

  app:
    build:
      context: .
    env_file:
      - .env_example
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db