"""Change name Comic to Comics and add new columns

Revision ID: d1eb9f782d52
Revises: 27c9c6f6529c
Create Date: 2024-03-19 15:57:45.566171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1eb9f782d52'
down_revision: Union[str, None] = '27c9c6f6529c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('count_of_ratings', sa.Integer(), nullable=True, server_default='0'),
    sa.Column('total', sa.Integer(), nullable=True, server_default='0'),
    sa.Column('rating', sa.Float(), nullable=True, server_default='0.0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comics_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comics_id'], ['comics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('comics')
    # ### end Alembic commands ###
